### ISSUE TITLE
Move development to WMF Gerrit

### ISSUE THREAD

**Issue by adamwight** [MGdesigner/Mediawiki-IDSextension#6]
Since this extension only exists for the purpose of integrating the Java backend with MediaWiki, we should create a WMF Gerrit repo and treat that as the master for further development.

I've started a request here: https://www.mediawiki.org/wiki/Git/New_repositories/Requests
However, QChrisNonWMF is waiting for confirmation that @MGdesigner is okay with this plan.  A note here or at the New Repositories page above should be plenty!

**Comment by MGdesigner** [comment]
Hi, adamwight, I am ok with this plan.  How should I go ahead？

**Comment by samwilson** [comment]
This is also covered in this Phabricator ticket: https://phabricator.wikimedia.org/T153989

**Comment by somechris** [comment]
Done.

The repo in WMF's gerrit is at https://gerrit.wikimedia.org/r/#/admin/projects/mediawiki/extensions/Ids

**Comment by MGdesigner** [comment]
ok I close the issue.
